[[news]]
date = "2026-06"
content = "My first-authored paper **Does festival memory stay the same? Investigating memory distortion through reappraisal** was accepted to *Journal of Hospitality and Tourism Management*."

[[news]]
date = "2026-02"
content = "My co-authored paper **Experience Therapy: How Service Experiences Regulate Everyday Negative Affect** was accepted to *Psychology & Marketing*."

[[news]]
date = "2025-11"
content = "My first-authored paper **Enhancing the Effectiveness of Generative AI Travel Recommendations: Balancing Source Credibility and Cognitive Load** was accepted to *Journal of Hospitality & Tourism Research*."

[[news]]
date = "2025-09"
content = "My co-authored paper **Mass customization and consumer behaviors: Exploring the roles of perceived value, perceived cost, and time pressure** was accepted to *International Journal of Hospitality Management*."

[[news]]
date = "2025-07"
content = "I successfully passed my Ph.D. Preliminary Exam."

[[news]]
date = "2025-06"
content = "I am honored received the **Best Dissertation Proposal Award** at **ICHRIE Annual Dissertation Competition**,organized by ICHRIE FutureFund."

[[news]]
date = "2024-11"
content = "My first-authored paper **Chatbots in complaint handling: the moderating role of humor** was accepted to *International Journal of Contemporary Hospitality Management*."

[[news]]
date = "2024-03"
content = "My first-authored working paper, *Turning Shadows into Spotlight: The Transformative Power of Memory Distortion in Shaping Positive Festival Experience*, received the **Best Paper Award** at SECSA CHRIE."

[[news]]
date = "2023-07"
content = "My first-authored paper **‘Platform stress’: exploring a new type of stress in the sharing economy** was accepted to *Current Issues in Tourism*."

[[news]]
date = "2023-04"
content = "I won **first prize** in the **Global Collegiate Marketing Case Competition**, organized by the HSMAI Foundation."

[[news]]
date = "2022-08"
content = "I began my Ph.D. program at **Purdue University** as a recipient of the **Ross Fellowship**."

[[news]]
date = "2022-08"
content = "I completed my Master’s degree in Hospitality Management at Kyung Hee University."

# [[news]]
# date = "2020-09"
# content = "I started my Master’s program at Kyung Hee University."

[[news]]
date = "2020-02"
content = "I concluded my role as a consultant at **EY Consulting**."
